### ISSUE TITLE
config fact cannot be fetched if config contains "forward-error-correction" command

### ISSUE THREAD

**Issue by ewenmcneill** [ansible-collection-migration/dellemc_networking.os6#52]
##### SUMMARY

The error detection code in Ansible `ansible/netcommon/plugins/connection/network_cli.py` used by the Dell OS6 modules detects errors by matching a series of regexes, one of which contains `b'(\bError\b)'`.  It is matched case insensitively, and thus matches valid Dell OS6 config like:

```
forward-error-correction enable-fec-cl108
```

falsely detecting an error in obtaining the config, when in fact the "error" text is within the config.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`ansible_collections/dellemc/os6/plugins/modules/os6_config.py`
`ansible_collections/ansible/netcommon/plugins/connection/network_cli.py`

##### ANSIBLE VERSION

```
(ansible) [ewen@castle ansible]$ ansible --version
ansible 2.10.17
  config file = /home/ewen/switch-setup/etc/ansible.cfg
  configured module search path = ['/home/ewen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ewen/ansible/lib64/python3.6/site-packages/ansible
  executable location = /home/ewen/ansible/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
(ansible) [ewen@castle ansible]$ 
```

##### COLLECTION VERSION

```
(ansible) [ewen@castle ansible]$ ansible-galaxy collection list dellemc.os6

# /home/ewen/ansible/lib64/python3.6/site-packages/ansible_collections
Collection  Version
----------- -------
dellemc.os6 1.0.7  

# /home/ewen/ansible/lib/python3.6/site-packages/ansible_collections
Collection  Version
----------- -------
dellemc.os6 1.0.7  
(ansible) [ewen@castle ansible]$ ansible-galaxy collection list ansible.netcommon

# /home/ewen/ansible/lib64/python3.6/site-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 3.0.1  

# /home/ewen/ansible/lib/python3.6/site-packages/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 3.0.1  
(ansible) [ewen@castle ansible]$ 
```

##### CONFIGURATION

```
(ansible) [ewen@castle ansible]$ ansible-config dump --only-changed
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATHS) = ['/home/ewen/ansible/lib/pyt
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = ['/home/ewen/switch-setup/hosts']
DEFAULT_STDOUT_CALLBACK(/home/ewen/switch-setup/etc/ansible.cfg) = defaultsummar
TRANSFORM_INVALID_GROUP_CHARS(/home/ewen/switch-setup/etc/ansible.cfg) = ignore
(ansible) [ewen@castle ansible]$ 
```

##### OS / ENVIRONMENT

Ansible host is ansible 2.10 installed from PIP on CentOS 7, with Python 3.6 (Ansible 2.10 is last version supported by Python 3.6; Python 3.6 is highest Python built into CentOS 7).

Target switch is Dell N2248X-ON, which has 4 x 25G interfaces.  Two of these on the target switch have 25GBase-LR SFP28s in them, which need FEC CL108-RS enabled on them (it is not enabled by "inherit") to bring up a 25G link to a Dell S5248F (which defaults to CL108-RS FEC on 25GBase-LR interfaces).

##### STEPS TO REPRODUCE

Configure a Dell OS6 N2248X-ON switch with at least one port with the config:

```
new-2248x#show running-config interface Tw1/0/1

speed 25000
forward-error-correction enable-fec-cl108
duplex full
flowcontrol receive off

new-2248x#
```

(which is the minimal config required to bring up a 25G link to the default S5248F switch).

Run Ansible command to gather the config:

```yaml
- name: "Dell OS6 | Gather network facts"
  become: yes
  os6_facts:
    gather_subset:
      - config

- debug:
    msg: "{{ansible_net_config}}"
```

##### EXPECTED RESULTS

The config for the switch would be returned, and available in `ansible_net_config`.

##### ACTUAL RESULTS

The config is not  available in `ansible_net_config`.

Instead ultimately (and this took a *lot* of debugging to find) the `ansible_collections/ansible/netcommon/plugins/connection/network_cli.py` function ` _find_error()` declares the Dell OS6 config response to be an error because the regex:

```
((\bout of range\b)|(\bnot found\b)|(\bCould not\b)|(\bUnable to\b)|(\bCannot\b)|(\bError\b)).*
```

matches, case insensitively, on the config, because it contains the text `error` in the middle of configuration command in the otherwise validly received config.  This ultimately results in a `ansible.errors.AnsibleConnectionFailure` being thrown, which results in a JSON RPC Internal Error (-32603), which results in the config output being returned in `err` instead of `out`, which results in `ansible_net_config` being empty.

Amusingly, the `os6_facts` step still succeeds, and the missing config is only noticed later when trying to parse things out of it.

While the utlimately failure is within `ansible.netcommon`, this particular config is required by the Dell OS6 switch configuration (which uses `forward-error-correction` instead of `fec` like the Dell OS10 / S series), so I think the Dell OS6 module will need to work around this mishandling of the config.

```
 3.4s _find_error: 
      "find_error: Oh no, its an error"='find_error: Oh no, its an error'
 3.4s _find_error: 
      stderr_regex.pattern=b'((\\bout of range\\b)|(\\bnot found\\b)|(\\bCould not\\b)|(\\bUnable to\\b)|(\\bCannot\\b)|(\\bError\\b)).*' (file:///tmp/q61872657.txt)
 3.4s _find_error: 
      stderr_regex.search(response)=<_sre.SRE_Match object; span=(8046, 8080), match=b'error-correction enable-fec-cl108\r'>
```

**Comment by ewenmcneill** [comment]
FTR, looks like this is a Dell OS6 specific case of:

https://docs.ansible.com/ansible/devel/network/user_guide/network_debug_troubleshooting.html#task-failure-due-to-mismatched-error-regex-within-command-response-using-ansible-netcommon-network-cli-connection-type

(although because `os6_facts` ignores the confg error, it's not actually a task failure).

Apparently there are work arounds via:

'The terminal plugin regex options ansible_terminal_stderr_re and ansible_terminal_stdout_re have pattern and flags as keys. The value of the flags key should be a value that is accepted by the re.compile python method"

so providing more Dell OS6 appropriate regexes that do not falsely match the config would hopefully work around this issue.

Ewen

**Comment by ewenmcneill** [comment]
After some more digging, the broken regex does come from the `dellemc.os6` collection:

https://github.com/ansible-collections/dellemc.os6/blob/eb8fee1d4acebb5186bbfbd56169ff6d51831c1d/plugins/terminal/os6.py#L48

which means this is a DellEMC OS6 bug, not a netcommon bug.

Fortunately, one can set `ansible_terminal_stderr_re` in the facts to override the default list; so I'm going to try doing that.

Ewen

**Comment by ewenmcneill** [comment]
FWIW, I apprear to have worked around this bug by setting a fact for the relevant switch (group) which repeats all the regexes from the Dell OS6 config:

https://github.com/ansible-collections/dellemc.os6/blob/eb8fee1d4acebb5186bbfbd56169ff6d51831c1d/plugins/terminal/os6.py#L39-L51

into a variable pattern, with additional escaping of the backslashes (thanks YAML), and just forcing the failing `(\bError\b)` match to be case sensitive instead of case insensitive.  Ie with `flags: 're.I`' on it, the config is not properly fetched; without `flags: 're.I'` the config is properly fetched.  There is no documentation for why `flags: 're.I'` was set on that specific match, so for now I'm assuming it's properly not important.  (If it is important, another more specific match should be added, not one that just generically matches regular config.)

Ewen

```
ansible_terminal_stderr_re:
  - pattern: "% ?Bad secret"
  - pattern: "(\\bInterface is part of a port-channel\\b)"
  - pattern: "(\\bThe maximum number of users have already been created\\b)|(\\bUse '-' for range\\b)"
  - pattern: "(?:incomplete|ambiguous) command"
    flags: 're.I'
  - pattern: "connection timed out"
    flags: 're.I'
  - pattern: "\\bParameter length should be exactly 32 characters\\b"
  - pattern: "'[^']' +returned error code: ?\\d+"
  - pattern: "Invalid|invalid.*$"
    flags: 're.I'
#
# Broken default Dell OS6 regex pattern; see
# https://github.com/ansible-collections/dellemc.os6/issues/52
#
# - pattern: "((\\bout of range\\b)|(\\bnot found\\b)|(\\bCould not\\b)|(\\bUnable to\\b)|(\\bCannot\\b)|(\\bError\\b)).*"
#   flags: 're.I'
#
# (Removing the case insensitive match here seems sufficient to avoid false
# triggers for now, so that is what we do.)
#
  - pattern: "((\\bout of range\\b)|(\\bnot found\\b)|(\\bCould not\\b)|(\\bUnable to\\b)|(\\bCannot\\b)|(\\bError\\b)).*"
  - pattern: "((\\balready exists\\b)|(\\bnot exist\\b)|(\\bnot active\\b)|(\\bFailed\\b)|(\\bIncorrect\\b)|(\\bnot enabled\\b)|(\\bDeactivate\\b)).*"
    flags: 're.I'
```
