### ISSUE TITLE
 "msg": "unable to retrieve current config",

### ISSUE THREAD

**Issue by mohit8888** [ansible-collection-migration/dellemc_networking.os6#60]
##### SUMMARY
'dellemc.os6.os6_config:" I am unable to use this module- I get the error msg- unable to retrieve current config  when the file os6.py line 103 has command "show running-config" if I shrink down the contents for the command with something like this"show running-config | begin snmp" it works, but that isnt the right way

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
dellemc.os6.os6_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = /Users/mbachhav/Documents/repos/rcode/ansible.cfg
  configured module search path = ['/Users/mbachhav/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/mbachhav/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.9/bin/ansible
  python version = 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) [Clang 6.0 (clang-600.0.57)] (/Library/Frameworks/Python.framework/Versions/3.9/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /Users/mbachhav/.ansible/collections/ansible_collections
Collection  Version
----------- -------
dellemc.os6 1.0.7  

# /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible_collections
Collection  Version
----------- -------
dellemc.os6 1.0.7  
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /Users/mbachhav/Documents/repos/rcode/ansible.cfg
DEFAULT_FORKS(/Users/mbachhav/Documents/repos/rcode/ansible.cfg) = 15
DEFAULT_HOST_LIST(/Users/mbachhav/Documents/repos/rcode/ansible.cfg) = ['/Users/mbachhav/Documents/repos/rcode/hosts']
DEPRECATION_WARNINGS(/Users/mbachhav/Documents/repos/rcode/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/mbachhav/Documents/repos/rcode/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Dell Switch OS  6.5.1.1 

##### STEPS TO REPRODUCE

```yaml

- name: get runnig config from dell 2048
  gather_facts: no
  hosts: switch1
  collections:
   - dellemc.os6
  tasks:
   - name: Change hostname
     dellemc.os6.os6_config:
      commands:
            -  hostname ANSIBLE-os6-2048
      save: True
      update: merge



```

##### ACTUAL RESULTS

```paste below


The full traceback is:
  File "/Users/mbachhav/.ansible/collections/ansible_collections/dellemc/os6/plugins/module_utils/network/os6.py", line 108, in get_config
    return _DEVICE_CONFIGS[cmd]





    "msg": "unable to retrieve current config",
```

**Comment by awesomekyle** [comment]
I'm seeing the same thing, but can't seem to find a workaround. Filtering the output doesn't seem to help. I can repro with every role:

```
- hosts: dell-switch
  strategy: linear
  gather_facts: false
  force_handlers: true
  roles:
    - dellemc.os6.os6_aaa
```
