### ISSUE TITLE
Description for lag/port-channel

### ISSUE THREAD

**Issue by s0ne** [ansible-collection-migration/dellemc_networking.os6#62]
##### SUMMARY
- Description for lag interface

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
os6_lag

##### ADDITIONAL INFORMATION

```yaml
os6_lag:
  po 100:
    type: dynamic
    state: present
    description: "Uplink Core"
    channel_members:
      - port: Tw1/0/1
        state: present
      - port: Tw2/0/2
        state: present    
```
